name: myapp
description: "Yum Inventory - Offline-first Inventory Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: any
  path_provider: any
  path: any
  http: any
  provider: any
  connectivity_plus: any
  intl: any

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
